CREATE TABLE articles(id INTEGER NOT NULL auto_increment, guid VARCHAR NOT NULL, uri VARCHAR(256), ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX IDX_ARTICLES_GUID ON articles(guid);
CREATE TABLE words(id INTEGER NOT NULL auto_increment, word VARCHAR(255), num VARCHAR(255), usage INTEGER DEFAULT 0);
CREATE UNIQUE INDEX IDX_WORDS_WORD ON words(word);